HW6: HW6.cpp
	g++ -o HW6 HW6.cpp -std=c++17 -O3 -march=native -fopenmp -DNDEBUG -I/usr/include/eigen3 -I/usr/local/boost_1_89_0/include -I/usr/local/include -L/usr/local/lib -lgsl -lgslcblas -lm
.PHONY: all run
all: HW6
run: HW6
	./HW6